version: "3"

includes:
  web:
    taskfile: ~/github/webserver-personal/Taskfile.yml
    dir: ~/github/webserver-personal
    optional: true

tasks:
  run:
    desc: "Run locally"
    cmds:
      - quarto preview

  deploy:manual:
    desc: "Deploy manually to the webserver"
    cmds:
      - quarto render
      - task: web:deploy-static
        vars:
          STATIC_DIR: _site
          SITE_NAME: aot-quarto
          PROJECT_DIR: "{{.TASKFILE_DIR}}"
          SSH_NAME: "{{.SSH_NAME}}"
