name: Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    environment:
      name: production
      uses:

    steps:
      - name: Call reusable-deploy
        uses: TimChild/deploy-quarto-static-site.yml@main
        with:
          vps-ip: ${{ vars.DROPLET_IP }}
          site-name: ${{ vars.SITE_NAME }}
          uses-python: true
          uses-r: false
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-user: "webadmin"
